/**
 * The bill of materials, and the version it claims to describe.
 *
 * An SBOM is only worth generating if it names the right thing. The version
 * lives in three places — `package.json`, `src/version.ts` (which the FHIR
 * CapabilityStatement reports) and the SBOM's own root component — and a
 * release that bumps one and not the others produces a document that
 * confidently describes a build nobody shipped. That is the failure worth a
 * test: not that the file parses, but that it is about this code.
 *
 * Generated by `npm sbom`, which the package manager already in use provides,
 * so nothing here adds a dependency to a project whose whole dependency
 * posture is the point.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { VERSION } from "../src/version.ts";

const ROOT = new URL("../", import.meta.url);
const haveInstall = existsSync(fileURLToPath(new URL("node_modules", ROOT)));

interface Sbom {
  bomFormat?: string;
  specVersion?: string;
  metadata?: { component?: { version?: string; purl?: string } };
  components?: Array<{ purl?: string }>;
}

function sbom(): Sbom {
  const out = execFileSync("npm", ["sbom", "--sbom-format", "cyclonedx"], {
    cwd: fileURLToPath(ROOT),
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  return JSON.parse(out) as Sbom;
}

test(
  "the SBOM describes this version, and the three places that state it agree",
  { skip: haveInstall ? false : "no node_modules; run npm ci first" },
  () => {
    const manifest = JSON.parse(readFileSync(new URL("package.json", ROOT), "utf8")) as { version: string };
    const doc = sbom();

    assert.equal(doc.bomFormat, "CycloneDX");
    assert.ok(doc.specVersion, "the SBOM states no CycloneDX spec version");

    // The load-bearing one. A release that bumps package.json and forgets
    // src/version.ts ships a CapabilityStatement naming the wrong release,
    // and an SBOM naming the right one — two documents disagreeing about
    // which build a site is running.
    assert.equal(manifest.version, VERSION, "package.json and src/version.ts disagree about the version");
    assert.equal(
      doc.metadata?.component?.version,
      VERSION,
      "the SBOM's root component is not the version this code reports"
    );
  }
);

test(
  "the SBOM accounts for the optional drivers a default install carries",
  { skip: haveInstall ? false : "no node_modules; run npm ci first" },
  () => {
    // The engine core imports none of these, and lazily imports them only for
    // the sources that need one — which is why the README can say there is no
    // required runtime dependency. It is not the same claim as an empty
    // install: `npm ci` takes optional dependencies by default, so an ordinary
    // deployment has these and their transitive tree on disk whether or not a
    // single channel ever polls Postgres. Naming that is the entire job of the
    // document, so a change that quietly stopped listing them is a regression
    // in the SBOM rather than a tidier one.
    const manifest = JSON.parse(readFileSync(new URL("package.json", ROOT), "utf8")) as {
      optionalDependencies?: Record<string, string>;
    };
    const declared = Object.keys(manifest.optionalDependencies ?? {});
    assert.ok(declared.length > 0, "no optional dependencies declared; this test is about those");

    const purls = (sbom().components ?? []).map((c) => c.purl ?? "");
    for (const name of declared) {
      assert.ok(
        purls.some((p) => p.startsWith(`pkg:npm/${name}@`)),
        `${name} is an optional dependency a default install takes, and the SBOM does not list it`
      );
    }
  }
);
